version: "3"
services:
  fhirserver:
    image: fhir-server
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: always
    environment:
      - FHIR_DATASOURCE_URL=${FHIR_DATASOURCE_URL}
      - FHIR_DATASOURCE_USERNAME=${FHIR_DATASOURCE_USERNAME}
      - FHIR_DATASOURCE_PASSWORD=${FHIR_DATASOURCE_PASSWORD}
      - APP_VALIDATE_TOKEN_API=${APP_VALIDATE_TOKEN_API}
