server:
  port: 8080
  max-http-request-header-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
spring:
  main:
    allow-circular-references: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    check-location: true
  datasource:
    url: "${FHIR_DATASOURCE_URL}"
    username: "${FHIR_DATASOURCE_USERNAME}"
    password: "${FHIR_DATASOURCE_PASSWORD}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false

app:
  validate-token-api: "${APP_VALIDATE_TOKEN_API}"

hapi:
  fhir:
    cr:
      enabled: false
    cdshooks:
      enabled: true
      clientIdHeaderName: client_id
    openapi_enabled: true
    fhir_version: R4
    ig_runtime_upload_enabled: false
    advanced_lucene_indexing: false
    bulk_export_enabled: false
    bulk_import_enabled: false
    narrative_enabled: false
    mdm_enabled: false
    mdm_rules_json_location: "mdm-rules.json"
    custom-bean-packages: "ca.uhn.fhir.jpa.starter"
    custom-interceptor-classes: "ca.uhn.fhir.jpa.starter.util.AuthenticationInterceptor"
    cors:
      allow_Credentials: true
      allowed_origin:
        - "*"
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    retain_cached_searches_mins: 0
    reuse_cached_search_results_millis: -1
    tester:
      home:
        name: Local Tester
        server_address: "http://localhost:8080/fhir"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
    inline_resource_storage_below_size: 4000
